server:
  port: 8761

eureka:
  instance:
#    hostname: localhost
     hostname: 192.168.3.208
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/